apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
  namespace: default
  labels:
    deploymentName: <your-deployment-name>
spec:
  scaleTargetRef:
    name: <your-deployment-name>
  pollingInterval: 15  
  cooldownPeriod:  30 
  minReplicaCount: 1  
  maxReplicaCount: 10 
  triggers:
  - type: prometheus
    metadata:
      # Required
      serverAddress: <prometheus-server-address>
      metricName: access_frequency
      threshold: '3'
      query: sum(rate(http_requests[2m]))
